### ISSUE TITLE
linear_b.minoan.raw does not exist

### ISSUE THREAD

**Issue by clemsciences** [j-luo93/NeuroDecipher#1]
Hello,

I tried to use your notebook (https://github.com/j-luo93/NeuroDecipher/blob/master/notebooks/Linear_b_simplified.ipynb) but it failed because linear_b.minoan.raw does not exist. Will it be available?

**Comment by j-luo93** [comment]
Hi, sorry for missing your issue.  I just pushed the two raw files online. They were pulled from the big table in the pdf file [here](https://archive.org/details/LinearBLexicon/page/n5/mode/2up).
